export const  REGISTER_START = 'REGISTER_START'
export const   REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const WALLET_TOP_SUCCESS = 'WALLET_TOP_SUCCESS';
export const WALLET_TOP_FAIL =  'WALLET_TOP_FAIL';


export const STORE_EMAIL = 'STORE_EMAIL'
export const STORE_REG_EMAIL = 'STORE_REG_EMAIL';


export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';


export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS';
export const GET_WALLET_FAIL = 'GET_WALLET_FAIL';


