export const  REGISTER_START = 'REGISTER_START'
export const   REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const WALLET_TOP_SUCCESS = 'WALLET_TOP_SUCCESS';
export const WALLET_TOP_FAIL =  'WALLET_TOP_FAIL';


export const STORE_EMAIL = 'STORE_EMAIL'
export const STORE_REG_EMAIL = 'STORE_REG_EMAIL';


export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';


export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS';
export const GET_WALLET_FAIL = 'GET_WALLET_FAIL';


export const GET_SPARK_USERS_SUCCESS = 'GET_SPARK_USERS_SUCCESS';
export const GET_SPARK_USERS_FAIL = 'GET_SPARK_USERS_FAIL';

export const  STORE_SPARK_USER = 'STORE_SPARK_USER';
export const STORE_NON_SPARK = 'STORE_NON_SPARK';


export const STORE_COMMAND = 'STORE_COMMAND';
export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS';
export const  GET_ADMIN_FAIL  = 'GET_ADMIN_FAIL'